spring:
  datasource:
    url: jdbc:mysql://localhost:3306/used
    username: hanyujie
    password: 123456

#server:
#  port: 8080
#  forward-headers-strategy: native

server:
  servlet:
    session:
      persistent: true
      cookie:
        max-age: 30d
#    context-path: /api

mybatis:
  configuration:
    map-underscore-to-camel-case: true
